[theme]
# Primary accent color for interactive elements.
primaryColor = "#fdd6bd"

# Background color for the main content area.
backgroundColor = "#FFEEFE"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#f794a4"

# Color used for almost all text.
textColor = "#5E514A"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
